### ISSUE TITLE
Add config options for recovering corrupted database

### ISSUE THREAD

**Issue by pprishchepa** [wodby/mariadb#14]
These 2 config options are very useful in case we're trying to recover a corrupted database:
- https://mariadb.com/kb/en/library/innodb-system-variables/#innodb_force_recovery
- https://mariadb.com/kb/en/library/innodb-system-variables/#innodb_purge_threads

**Comment by csandanov** [comment]
was added in https://github.com/wodby/mariadb/releases/tag/3.4.0
