### ISSUE TITLE
PAM auth

### ISSUE THREAD

**Issue by sooslaca** [wodby/mariadb#15]
hi,

Would it be possible to add auth_pam? It's in the debian version by default.
```
root@c58c555fae11:/# ls -la /usr/lib/mysql/plugin/ | grep pam
-rw-r--r-- 1 root root  10512 May 13 19:06 auth_pam.so
```

If I'm right all you have to do is to install alpine package `linux-pam-dev` to build-deps and `linux-pam` to run-deps.

Thanks

**Comment by csandanov** [comment]
Added to latest, can be enabled via `$MARIADB_PLUGIN_LOAD=auth_pam `

**Comment by sooslaca** [comment]
Thanks @csandanov I tested and it works fine!

Some info for other users who might get here: `nss-pam-ldapd` should be also installed if you want mariadb to authenticate from ldap.

I think we can close this ticket, `pam` plugin has been added to the image.
