### ISSUE TITLE
I want to add 'connect_timeout' setting 

### ISSUE THREAD

**Issue by ainsofs** [wodby/mariadb#17]
see https://mariadb.com/kb/en/library/server-system-variables/#connect_timeout

currently there is no environment variable for that. can you provide some ways I can do this?

I need it so that I can upgrade from drupal 8.6 to 8.7 using this solution https://www.drupal.org/project/drupal/issues/3052464#comment-13142037

**Comment by csandanov** [comment]
Added `$MYSQL_CONNECT_TIMEOUT` although I don't think this need in this case, wait_timeout – maybe, but how on earth connect timeout is the issue
