### ISSUE TITLE
Increase open_files_limit mariadb variable

### ISSUE THREAD

**Issue by heyyoyo** [wodby/mariadb#18]
Hi guys,
I need to increase the variable open_files_limit, is it possible to have a new variable environment for it ?
Thanks.

**Comment by heyyoyo** [comment]
Strange it doesn't seem to set the variable.
I used MARIADB_TAG=latest in my .env file
In portainer inside mariadb container details I can see the environment variable MYSQL_OPEN_FILES_LIMIT with my value. But inside mysql the variable open_files_limit is still the defaut value I had before. 
I tried even really low value like 1000. but same thing no change applied.

**Comment by csandanov** [comment]
`latest` is 10.4 and is still building, we had some pam related issues with the recent upgrade, try `10.3` https://circleci.com/gh/wodby/mariadb

**Comment by heyyoyo** [comment]
I see thanks
