### ISSUE TITLE
linux-pam build failures

### ISSUE THREAD

**Issue by csandanov** [wodby/mariadb#20]
See https://jira.mariadb.org/browse/MDEV-20258.

Todo once fixed: 
- return linux pam packages
- remove creation of `/auth_pam_tool_dir/auth_pam_tool`, it's a workaround for 10.4 `mysql_install_db`
- recover pam plugin tests

**Comment by sooslaca** [comment]
hi @csandanov,

Found a possible solution at: https://github.com/MariaDB/mariadb-connector-c/blob/ed3a91c139175746c5d6903d67ca902d91228f65/include/ma_global.h#L269

Created a patch for us and put into /10/patches folder:
[pam_mariadb_mtr.c.patch.txt](https://github.com/wodby/mariadb/files/3511052/pam_mariadb_mtr.c.patch.txt)
(should be renamed to .patch, github doesn't like attaching .patch file)

At least it finishes compiling now :) What do you think?

**Comment by csandanov** [comment]
Thank you! The fix is available in 3.6.3 stability tag.
