### ISSUE TITLE
galera / wsrep?

### ISSUE THREAD

**Issue by tomalok** [wodby/mariadb#26]
It appears that this (10.4, at least) is not compiled to support Galera cluster.

Any reason why, besides perhaps you didn't need it for your use case?  Would like to know what I'm getting into before I embark on adding it on a fork/branch...

Thanks!

**Comment by csandanov** [comment]
no reason but we'll soon may need it

**Comment by tomalok** [comment]
I've just opened a merge request over at https://gitlab.alpinelinux.org/alpine/aports/merge_requests/3397 to add a galera package.  It builds for x86 and x86_64, but the patches (or at least the `musl-wordsize.patch`, the first one it comes across) don't work for the other arch's.

**Comment by csandanov** [comment]
We don't actually use alpine packages, we built it from source

**Comment by tomalok** [comment]
yep, i realize that -- but feel free to re-use (and/or improve) on those patches over there.

**Comment by tomalok** [comment]
I should have a PR that builds and adds `/usr/lib/libgalera_smm.so` soon-ish -- I got it to build last night, but noticed that it wasn't stripped yet.

**Comment by tomalok** [comment]
PR #28

**Comment by tomalok** [comment]
PR #28 should be ready for review.
