### ISSUE TITLE
Getting MyRocks storage engine available?

### ISSUE THREAD

**Issue by kevinquillen** [wodby/mariadb#27]
Since 10.2.5 MariaDB has support for MyRocks storage engine ([RocksDB](https://en.wikipedia.org/wiki/RocksDB)).

MariaDB has a [page on how to build the module needed](https://en.wikipedia.org/wiki/RocksDB) to make this storage engine available.

Assuming I want to experiment a bit and check it out, how I would I get this in using the wodby MariaDB image? Would I supply a Dockerfile that builds on to the process, or have to write/make my own image from scratch (i.e. not use wodby/mariadb)?

**Comment by csandanov** [comment]
You gave a link on wiki, did you meant to link https://mariadb.com/kb/en/building-myrocks-in-mariadb?

Did you actually try running this image with rocksdb?

**Comment by tomalok** [comment]
The rocksdb stuff appears to be building, at least.  I haven't tried using it -- I'm more focused on getting Galera in there... ;)
