### ISSUE TITLE
Return build of arm64 variants

### ISSUE THREAD

**Issue by csandanov** [wodby/mariadb#36]
Since 3.14.0 arm64 variant no longer built because cross-compiling no longer fits in gh actions's 6h build limit

**Comment by Dropa** [comment]
Is there any plan how this could be done? Any way we can help?

Would be highly appreciated to get arm64 variants. As we've been testing, arm64 based native mariadb images are blazing fast to work with on M1 Mac, but there seem to be other problems on native images that causes instability when used with wodby4drupal.

**Comment by jorgemuza** [comment]
+1

**Comment by heyyo-droid** [comment]
+ 1

**Comment by heyyo-droid** [comment]
Any update on m1 support ?

**Comment by kevinquillen** [comment]
Well this is extremely unfortunate, there must be a solution.

Does that mean that the images listed here without an ARM64 checkmark are not going to work on M1+ macs? 35% of our company is on M1/M2.

https://github.com/wodby/docker4drupal

Right now someone had to add a `docker-compose.override.yml` file and add this:

```
services: 
  mariadb:
    platform: linux/amd64
```

I really do not like that solution.

> the latest wodby/mariadb image that supports M1 is 10.4-3.13.21

I do not want to use a old database version either.

**Comment by Dropa** [comment]
> Right now someone had to add a `docker-compose.override.yml` file and add this:
> 
> ```
> services: 
>   mariadb:
>     platform: linux/amd64
> ```
> 
> I really do not like that solution.

Do not use this, it just forces you to use the wrong image.

Instead what you can do is use the original mariadb image, we've been using it without problems and it is significantly faster on M1

**Comment by mcrump001** [comment]
I was wondering if this issue was being revisited in light of the M1 larger runner support on GitHub:

https://github.blog/2023-10-02-introducing-the-new-apple-silicon-powered-m1-macos-larger-runner-for-github-actions/

**Comment by csandanov** [comment]
macos machines do not support cross-compilation

**Comment by csandanov** [comment]
linux/arm64 builds returned in 3.28.0
