### ISSUE TITLE
optimizer_search_depth=0

### ISSUE THREAD

**Issue by AexChecker** [wodby/mariadb#4]
Please add a settings for "optimizer_search_depth" (optimizer_search_depth=0), see
https://mariadb.com/resources/blog/setting-optimizer-search-depth-mysql

**Comment by csandanov** [comment]
Thanks! I've added both `MYSQL_OPTIMIZER_PRUNE_LEVEL` and `MYSQL_OPTIMIZER_SEARCH_DEPTH` (defaults to 62) with a commentary in README to decrease it if you have a lot of queries with 15+ tables. Currently available in latest versions, will be included in the upcoming stability tag release.
