### ISSUE TITLE
autosize rather than copy default values for system settings

### ISSUE THREAD

**Issue by grooverdan** [wodby/mariadb#45]
As @[ioanma](https://github.com/ioanma) found out in https://github.com/MariaDB/mariadb-docker/issues/413#issuecomment-1046228447, the setting of lower_case_table_names=0 in https://github.com/wodby/mariadb/commit/0f2c8ce53cede151c440877108e458288a1eee86 caused them to fail on start up.

What isn't clear in the documentation, is that `lower_case_table_names` isn't exactly a default value of 0 on unix, but an auto-determined default value based on `lower_case_file_system`. As the user has a lower case data directory, this now fails at startup.

MariaDB is going to continue to autoset these settings in a way that gets the best user experience. We really want to see an ideal scenario where only a small amount of tuning is needed.

I understand that you may occasionally want a different default for you users, however that should be a special case rather than just providing a environment variable with the current default value at the time of commit.

The current dangerous defaults I see on a very quick examination are:
* query_cache_type=ON (highly negative performance impact)
* innodb_flush_log_at_trx_commit=2 (data loss)
* join buffer size - [ref](https://mariadb.com/kb/en/block-based-join-algorithms/#size-of-join-buffers) since 10.4 is autosized based on rows
* innodb_open_files - now autosized

So as a feature request for our communities, can the default configuration files of wodby/mariadb work their way back to being a default, or where there is a divergence in configuration from default, this is documented in the configuration file for the awareness of the user, and you as a maintainer. As [nextcloud discovered](https://github.com/nextcloud/server/issues/25436), the use of non-defaults can result in hardship for the user communities.

**Comment by csandanov** [comment]
Hi, thank you for your recommendations. I've reworked defaults and introduced some new env vars to adjust it if needed.

**Comment by grooverdan** [comment]
thanks
