### ISSUE TITLE
New Long Term Support 10.11 is available

### ISSUE THREAD

**Issue by heyyo-droid** [wodby/mariadb#46]
I suppose the new version MariaDB 10.11 is the one we should use now. It's the new LTS, previously branch 10.6.

https://mariadb.com/kb/en/mariadb-server-release-dates/

**Comment by csandanov** [comment]
Was added in https://github.com/wodby/mariadb/releases/tag/3.26.0

**Comment by 3xploiton3** [comment]
please add LTS tag

example:
![image](https://github.com/wodby/mariadb/assets/19517680/5cd6595e-74f4-4071-b0eb-d2e6c212ec7c)
