### ISSUE TITLE
Manifest for wodby/mariadb:10.2-3.3.8 not found

### ISSUE THREAD

**Issue by rommaz** [wodby/mariadb#7]
Command `docker pull wodby/mariadb:10.2-3.3.8` results in following error `Error response from daemon: manifest for wodby/mariadb:10.2-3.3.8 not found`
Same command for `wodby/mariadb:10.1-3.3.8` and `wodby/mariadb:10.3-3.3.8` works fine.

I'm using Docker for Mac (version 18.06.1-ce-mac73 (26764))

**Comment by csandanov** [comment]
The build for 10.2 has failed due to some external services unavailability (probably docker registry), rebuilding now https://circleci.com/gh/wodby/mariadb/258

**Comment by csandanov** [comment]
it's all good now https://hub.docker.com/r/wodby/mariadb/tags/
